name: Windows Firefox via Ngrok (Browser Access)

on: [workflow_dispatch]

jobs:
  browser:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download Ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract Ngrok
        run: Expand-Archive ngrok.zip

      - name: Authenticate Ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Install Firefox
        run: |
          Invoke-WebRequest -Uri "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US" -OutFile firefox.exe
          Start-Process firefox.exe -ArgumentList "/silent" -Wait

      - name: Launch Firefox
        run: Start-Process "C:\Program Files\Mozilla Firefox\firefox.exe"

      - name: Start Ngrok Tunnel to Remote Desktop (optional)
        run: .\ngrok\ngrok.exe tcp 3389

      - name: Prevent Idle Timeout
        run: |
          for ($i = 0; $i -lt 720; $i++) {
            Write-Output "Anti-idle active... $i"
            Start-Sleep -Seconds 30
          }
