name: Ubuntu XFCE noVNC

on: [workflow_dispatch]

jobs:
  ubuntu-vnc:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Install Desktop & VNC
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies tightvncserver firefox
        vncserver :1
        vncserver -kill :1
        mkdir -p ~/.vnc
        echo -e "#!/bin/bash\nxrdb $HOME/.Xresources\nstartxfce4 &" > ~/.vnc/xstartup
        chmod +x ~/.vnc/xstartup
        echo "P@ssw0rd!" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd
        vncserver :1

    - name: Setup noVNC
      run: |
        sudo apt install -y git websockify python3-websockify
        git clone https://github.com/novnc/noVNC.git
        git clone https://github.com/novnc/websockify noVNC/utils/websockify
        nohup ./noVNC/utils/launch.sh --vnc localhost:5901 --listen 6080 &

    - name: Anti-Idle
      run: |
        while true; do echo "Running..."; sleep 60; done
