name: Ubuntu XFCE noVNC (cloudflared)

on: [workflow_dispatch]

jobs:
  start-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install XFCE and VNC
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver
          vncserver :1 || true
          vncserver -kill :1 || true
          mkdir -p ~/.vnc
          echo "#!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          echo 'UEBzc3cwcmQhCg==' | base64 -d > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1

      - name: Install noVNC and start server
        run: |
          sudo apt install -y git python3-websockify
          git clone https://github.com/novnc/noVNC.git
          git clone https://github.com/novnc/websockify noVNC/utils/websockify
          nohup ./noVNC/utils/launch.sh --vnc localhost:5901 --listen 6080 &

      - name: Install and run cloudflared tunnel
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          nohup cloudflared tunnel --url http://localhost:6080 > cloudflared.log 2>&1 &

      - name: Anti-idle (Prevent timeout)
        run: |
          while true; do echo "Running..."; sleep 60; done
