name: Ubuntu XFCE noVNC with Chrome

on: [workflow_dispatch]

jobs:
  start-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install XFCE, VNC, and Chrome
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver wget gnupg2
          
          # Install Google Chrome
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable

          # Setup VNC
          vncserver :1 || true
          vncserver -kill :1 || true
          mkdir -p ~/.vnc
          echo "#!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          echo 'UEBzc3cwcmQhCg==' | base64 -d > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1

      - name: Install noVNC and run
        run: |
          sudo apt install -y git python3-websockify
          git clone https://github.com/novnc/noVNC.git
          git clone https://github.com/novnc/websockify noVNC/utils/websockify
          nohup bash -c './noVNC/utils/launch.sh --vnc localhost:5901 --listen 6080' > novnc.log 2>&1 &

      - name: Setup ngrok tunnel
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          sleep 10
          nohup ngrok http 6080 > ngrok.log 2>&1 &

      - name: Anti-idle (Prevent timeout)
        run: |
          while true; do echo "Running..."; sleep 60; done
