name: Windows with Firefox (noVNC Access)

on: [workflow_dispatch]

jobs:
  desktop:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Install Chocolatey + Firefox
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          choco install firefox -y

      - name: Download and install TightVNC
        run: |
          Invoke-WebRequest https://www.tightvnc.com/download/2.8.81/tightvnc-2.8.81-gpl-setup-64bit.msi -OutFile tightvnc.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i tightvnc.msi /quiet'

      - name: Set VNC Password
        run: |
          cmd /c "echo P@ssw0rd! > pass.txt"
          & "C:\Program Files\TightVNC\tvnserver.exe" -controlapp -passwordfile .\pass.txt

      - name: Download and start Ngrok TCP Tunnel
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .
          .\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
          Start-Process .\ngrok.exe -ArgumentList "tcp 5900"
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Anti-idle
        run: |
          for ($i = 0; $i -lt 720; $i++) {
            Write-Output "Keeping alive... $i"
            Start-Sleep -Seconds 30
          }
